package audio

import (
	"encoding/binary"
	"fmt"
	"os"
	"sync"

	"github.com/hajimehoshi/oto/v2"
)

// AYSource is the minimal interface that the audio system needs from an AY
// sound chip implementation. It is satisfied by *ay.AY and *ay.Engine but kept
// as an interface here so the audio package does not need to import the ay
// package (which would create a dependency cycle through the ULA).
//
// The buffer is interleaved stereo, because an AY is a stereo source on this
// hardware: the Next pans its three channels per NR$08 bit 5 and NR$09 bits
// 7:5 (turbosound.vhd), and a chip left in mono simply writes the same value
// to both slots.
type AYSource interface {
	MixIntoStereo(buf []int16)
}

// DACSource is the minimal interface for the Spectrum Next's four
// 8-bit DACs. Satisfied by *next/dac.Bank. Mixes at frame-snapshot
// granularity: the current level is applied uniformly across the
// whole buffer rather than integrating individual writes within
// the frame (contrast pkg/audiodac's event-based reconstruction).
//
// Interleaved stereo for the same reason: soundrive.vhd sums channels A and B
// into the left output and C and D into the right, so the bank has a real
// stereo image and folding it down here would discard it.
type DACSource interface {
	MixIntoStereo(buf []int16)
}

const (
	// Audio parameters
	SampleRate   = 44100
	ChannelCount = 2    // Stereo
	BitDepth     = 16   // 16-bit
	BufferSize   = 1024 // oto buffer size in samples — small enough that Read() runs ~43 times/sec, keeping playback latency low

	// SamplesPerFrame is the number of audio frames one emulator frame
	// produces at SampleRate / 50Hz, counted PER CHANNEL. A producer pushing
	// stereo therefore hands over SamplesPerFrame*ChannelCount int16 values.
	SamplesPerFrame = SampleRate / 50

	// queueCapacity is the ring buffer size in int16 slots. Two slots make one
	// stereo frame, so this is about 12 emulator frames at 50Hz (~240 ms):
	// wide enough to absorb scheduler jitter, GC pauses, and the natural
	// push/pull oscillation between the 50Hz producer and the ~43Hz consumer.
	//
	// Everything below counts SLOTS, not frames, and the ring is kept
	// frame-aligned by only ever moving the head and tail two at a time. A
	// single-slot move would rotate the interleave, turning one dropped sample
	// into a permanent left/right swap for the rest of the session.
	queueCapacity = SamplesPerFrame * ChannelCount * 12

	// queuePrefill is how many silent slots we seed the queue
	// with at startup so the consumer's first pull doesn't drain
	// the queue to zero. Without this cushion, the producer is
	// always exactly one push behind the consumer (they have equal
	// average rates but different periods), and every pull cycle
	// returns a partial buffer plus DC silence — audible as
	// stutter at the consumer's pull rate. Four frames give the
	// queue enough headroom that the discrete-event oscillation
	// never reaches the bottom.
	queuePrefill = SamplesPerFrame * ChannelCount * 4
)

// prefillSilence indexes queue (a [queueCapacity]int16 array) directly over
// [0, queuePrefill); this compile-time check keeps that in bounds if either
// constant's multiplier above is ever changed on its own.
var _ [queueCapacity - queuePrefill]struct{}

// AudioSystem handles audio output for the ZX Spectrum beeper and (on 128K+
// machines) the AY-3-8912 sound chip.
//
// The beeper input is event-driven: the ULA records every speaker bit
// toggle during the frame with the T-state at which it happened, and at
// end of frame generates a fresh batch of SamplesPerFrame mono samples
// that gets pushed via PushBeeperSamples. The oto playback callback
// pulls samples from the ring buffer; on underflow it holds the last
// sample (DC) instead of clicking.
//
// The AY chip is mixed in by the playback callback at audio-sample
// rate via AYSource.MixInto, since AY samples are generated by the
// chip's own internal counters and don't need event-time alignment.
type AudioSystem struct {
	context *oto.Context
	player  oto.Player
	reader  *audioReader

	// Interleaved stereo sample ring buffer. All four counters are in int16
	// slots and always move in pairs, so the ring never loses frame alignment.
	queueMu   sync.Mutex
	queue     [queueCapacity]int16
	queueHead int // next write slot
	queueTail int // next read slot
	queueSize int // slots currently in the buffer

	// lastL/lastR are held during underflow (DC, no clicks), one per channel.
	// A single shared value would collapse the stereo image to mono for the
	// length of every buffer starve.
	lastL, lastR int16

	// Optional AY-3-8912 source.
	ayMu sync.RWMutex
	ay   AYSource

	// Optional Spectrum Next DAC source.
	dacMu sync.RWMutex
	dac   DACSource

	// keepAlive is the peak amplitude of the sub-audible dither mixed into the
	// output to stop the host audio amp powering down during silence (and
	// popping on the next sound). 0 disables. Read/written only on the oto
	// goroutine path + setup, so a plain field is fine.
	keepAlive int16

	// WAV recording state. When recFile is non-nil the audio reader
	// appends each generated sample to the file as 16-bit mono PCM.
	recMu      sync.Mutex
	recFile    *os.File
	recSamples uint64
	recScratch []byte

	// silent marks a mixer with no oto output device: nothing is played and
	// the oto playback goroutine never pulls. PumpFrames — called once per
	// executed frame by the emulator's frame loop — becomes the sole
	// consumer of audioReader.Read, so the mix (beeper events, AY, DAC) and
	// the WAV recorder still run on a machine with no sound card, or in
	// headless mode where there is no audio context at all.
	silent bool

	// pumpBuf is PumpFrames' scratch buffer: it receives the little-endian
	// bytes of each pumped frame, which are discarded — the recording was
	// already written from the int16 mix inside Read.
	pumpBuf []byte
}

// audioReader implements io.Reader on the oto playback goroutine.
type audioReader struct {
	audioSys  *AudioSystem
	buffer    []byte
	mixBuffer []int16
	ditherRNG uint32 // xorshift32 state for the keep-alive dither
}

// oto permits exactly ONE audio context per process — a second
// oto.NewContext call crashes the audio driver. The context is also
// never torn down (Close only stops the player), so it is a natural
// process-singleton: created once, reused by every AudioSystem.
// This keeps GUI model switches (which build a fresh AudioSystem)
// and multi-test runs (each constructing emulators) from creating a
// second context and SIGSEGV-ing in the oto mux loop.
var (
	sharedCtxOnce sync.Once
	sharedCtx     *oto.Context
	sharedCtxErr  error
)

func sharedAudioContext() (*oto.Context, error) {
	sharedCtxOnce.Do(func() {
		ctx, ready, err := oto.NewContext(SampleRate, ChannelCount, oto.FormatSignedInt16LE)
		if err != nil {
			sharedCtxErr = err
			return
		}
		<-ready
		sharedCtx = ctx
	})
	return sharedCtx, sharedCtxErr
}

// New creates a new AudioSystem instance.
func New() (*AudioSystem, error) {
	ctx, err := sharedAudioContext()
	if err != nil {
		return nil, fmt.Errorf("failed to create audio context: %w", err)
	}

	as := &AudioSystem{context: ctx, keepAlive: defaultKeepAliveLevel}
	as.reader = &audioReader{
		audioSys: as,
		buffer:   make([]byte, BufferSize*ChannelCount*2),
		// One slot per int16 the buffer above can hold, so Read never has to
		// grow this on the oto callback goroutine.
		mixBuffer: make([]int16, BufferSize*ChannelCount),
		ditherRNG: 0x9E3779B9, // any non-zero seed
	}
	as.prefillSilence()
	as.player = ctx.NewPlayer(as.reader)
	return as, nil
}

// NewSilent creates an AudioSystem with NO oto output device — the
// headless / no-sound-card variant. The whole mix pipeline (beeper event
// synthesis, AY and DAC mixing, WAV recording) runs identically to the
// device-backed New(); the only difference is who calls audioReader.Read:
// instead of the oto playback goroutine pulling at device rate, the
// emulator's frame loop calls PumpFrames once per executed frame, so the
// WAV advances in emulated time whether or not a sound card exists.
//
// Returns *AudioSystem directly (never errors): there is no device to fail.
func NewSilent() *AudioSystem {
	as := &AudioSystem{keepAlive: 0, silent: true}
	as.reader = &audioReader{
		audioSys:  as,
		buffer:    make([]byte, BufferSize*ChannelCount*2),
		mixBuffer: make([]int16, BufferSize*ChannelCount),
		ditherRNG: 0x9E3779B9,
	}
	// No prefill cushion: PumpFrames consumes exactly the one frame each
	// flushAudioFrame push produced, one-for-one. The cushion that keeps a
	// real device from starving would only surface in the WAV as leading
	// silence here — and silence is what an empty queue emits anyway.
	as.queueHead, as.queueTail, as.queueSize = 0, 0, 0
	as.lastL, as.lastR = 0, 0
	return as
}

// IsSilent reports whether this system runs without an output device and
// must be driven by PumpFrames (see NewSilent).
func (as *AudioSystem) IsSilent() bool { return as.silent }

// PumpFrames consumes n emulated frames of audio from the mixer without an
// output device, running the same Read path the oto goroutine would: pop
// the beeper frame the ULA pushed this frame, mix AY + DAC at sample rate,
// append to any active WAV recording. The emitted little-endian bytes go
// into a scratch buffer and are discarded — there is no speaker on the
// other end; the WAV is the point.
//
// Frames are pumped whole (SamplesPerFrame stereo frames at a time) to stay
// frame-aligned with the producer; popping a partial frame would desync the
// queue against every future flush.
func (as *AudioSystem) PumpFrames(frames int) {
	if frames <= 0 || as.reader == nil {
		return
	}
	if len(as.pumpBuf) == 0 {
		as.pumpBuf = make([]byte, SamplesPerFrame*ChannelCount*2)
	}
	for i := 0; i < frames; i++ {
		_, _ = as.reader.Read(as.pumpBuf)
	}
}

// prefillSilence seeds the ring buffer with queuePrefill silent
// samples so the consumer's first few pulls are satisfied without
// draining the queue. See the queuePrefill doc comment for the rate-
// matching reasoning.
func (as *AudioSystem) prefillSilence() {
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	as.queueHead = queuePrefill % queueCapacity
	as.queueTail = 0
	as.queueSize = queuePrefill
	for i := 0; i < queuePrefill; i++ {
		as.queue[i] = 0
	}
	as.lastL, as.lastR = 0, 0
}

// pushFrame appends one stereo frame. On overflow the oldest FRAME is dropped,
// never a single slot: audio glitches are preferable to growing latency, but a
// half-frame drop would rotate the interleave and swap the channels for good.
// Caller holds queueMu.
func (as *AudioSystem) pushFrame(l, r int16) {
	as.queue[as.queueHead] = l
	as.queue[(as.queueHead+1)%queueCapacity] = r
	as.queueHead = (as.queueHead + 2) % queueCapacity
	if as.queueSize == queueCapacity {
		as.queueTail = (as.queueTail + 2) % queueCapacity
	} else {
		as.queueSize += 2
	}
}

// PushBeeperSamples enqueues a batch of MONO samples generated by the ULA at
// end of frame, placing each on both channels.
//
// Mono is the honest shape for this input rather than a shortcut. The
// Spectrum's beeper is one bit driving one speaker, and everything the ULA
// folds into this frame before pushing — the tape's EAR waveform, SpecDrum,
// Covox — is a single-ended source too. Sources with a real stereo image use
// PushStereoSamples.
func (as *AudioSystem) PushBeeperSamples(samples []int16) {
	if len(samples) == 0 {
		return
	}
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	for _, s := range samples {
		as.pushFrame(s, s)
	}
}

// PushStereoSamples enqueues interleaved stereo frames (L, R, L, R ...).
// A trailing odd slot is ignored rather than pushed as half a frame.
func (as *AudioSystem) PushStereoSamples(interleaved []int16) {
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	for i := 0; i+1 < len(interleaved); i += 2 {
		as.pushFrame(interleaved[i], interleaved[i+1])
	}
}

// underrunDecayNum/underrunDecayDen is the per-sample multiplier applied to
// the held level while the ring buffer is starved. ~255/256 gives a ~6 ms
// time constant: a brief gap is essentially held, but a sustained drain (a
// pause, a model switch, or a heavy fast-load tick that starves the producer)
// fades to silence rather than holding a flat DC plateau — a flat plateau
// would step abruptly back to the signal when production resumes, audible as
// a click.
const (
	underrunDecayNum = 255
	underrunDecayDen = 256
)

// decayHeld shrinks a held level one step toward silence.
func decayHeld(v int16) int16 {
	return int16(int32(v) * underrunDecayNum / underrunDecayDen)
}

// popStereoSamples drains up to len(out) slots from the ring buffer into out,
// a frame at a time. Any unfilled frames continue from the last delivered one
// and then decay toward 0 PER CHANNEL, so underruns fade to silence smoothly
// instead of clicking, and without the image collapsing to the centre on the
// way down. A trailing odd slot in out is left untouched.
func (as *AudioSystem) popStereoSamples(out []int16) {
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	n := 0
	for n+1 < len(out) && as.queueSize > 0 {
		out[n] = as.queue[as.queueTail]
		out[n+1] = as.queue[(as.queueTail+1)%queueCapacity]
		as.queueTail = (as.queueTail + 2) % queueCapacity
		as.queueSize -= 2
		n += 2
	}
	if n > 0 {
		as.lastL, as.lastR = out[n-2], out[n-1]
	}
	for ; n+1 < len(out); n += 2 {
		out[n], out[n+1] = as.lastL, as.lastR
		as.lastL, as.lastR = decayHeld(as.lastL), decayHeld(as.lastR)
	}
}

// Read implements io.Reader for the audioReader. Pulls interleaved stereo
// frames from the ring buffer, mixes in any attached AY chip and DAC bank, and
// hands the result to the oto sink.
//
// This mirrors audio_mixer.vhd, which sums the beeper, the AY pair and the DAC
// pair into pcm_L_o / pcm_R_o. Each stage below adds into the same interleaved
// buffer, so a source that is mono simply contributes equally to both slots.
func (ar *audioReader) Read(p []byte) (n int, err error) {
	bytesToRead := len(p)
	if bytesToRead > len(ar.buffer) {
		bytesToRead = len(ar.buffer)
	}
	// Round down to whole stereo frames. Every stage below stops at the last
	// complete frame, so an odd slot would be left holding whatever the
	// previous call put there — mixBuffer is reused — and that stale sample
	// would be dithered, recorded and emitted.
	slots := (bytesToRead / 2) &^ 1
	bytesToRead = slots * 2

	if cap(ar.mixBuffer) < slots {
		ar.mixBuffer = make([]int16, slots)
	}
	mixBuf := ar.mixBuffer[:slots]

	// Step 1: pull the beeper/tape/DAC frame the ULA pushed.
	ar.audioSys.popStereoSamples(mixBuf)

	// Step 2: mix in the AY chip's output (it generates samples
	// from its own internal counters at audio rate).
	ar.audioSys.ayMu.RLock()
	ay := ar.audioSys.ay
	ar.audioSys.ayMu.RUnlock()
	if ay != nil {
		ay.MixIntoStereo(mixBuf)
	}

	// Step 2.5: mix in the Next DAC bank if attached (frame-snapshot
	// granularity — see DACSource).
	ar.audioSys.dacMu.RLock()
	dac := ar.audioSys.dac
	ar.audioSys.dacMu.RUnlock()
	if dac != nil {
		dac.MixIntoStereo(mixBuf)
	}

	// Step 3: WAV recording — append the mix before the keep-alive dither, so
	// captures stay clean for diagnostics.
	ar.audioSys.writeRecording(mixBuf)

	// Step 3.5: keep-alive dither — a sub-audible noise floor that stops the
	// host audio amp powering down during silence and popping on the next
	// sound. Added to the device output only.
	applyKeepAliveDither(mixBuf, ar.audioSys.keepAlive, &ar.ditherRNG)

	// Step 4: emit as little-endian bytes. The buffer is already interleaved,
	// so this is a straight widening with no channel decision left to make.
	for i := 0; i < slots; i++ {
		s := mixBuf[i]
		ar.buffer[i*2] = byte(s)
		ar.buffer[i*2+1] = byte(s >> 8)
	}
	copy(p, ar.buffer[:bytesToRead])
	return bytesToRead, nil
}

// Start begins audio output. A silent system (NewSilent) has no player and
// no device — there is nothing to start, and the frame loop pumps it.
func (as *AudioSystem) Start() error {
	if as.player == nil {
		return nil
	}
	as.player.Play()
	return nil
}

// Stop pauses audio output.
func (as *AudioSystem) Stop() {
	if as.player != nil {
		as.player.Pause()
	}
}

// SetAY attaches an AY-3-8912 source whose output will be mixed into
// the beeper stream. Pass nil to detach.
func (as *AudioSystem) SetAY(ay AYSource) {
	as.ayMu.Lock()
	defer as.ayMu.Unlock()
	as.ay = ay
}

// SetDAC attaches a Spectrum Next DAC bank whose output will be
// mixed into the beeper + AY stream. Pass nil to detach.
func (as *AudioSystem) SetDAC(dac DACSource) {
	as.dacMu.Lock()
	defer as.dacMu.Unlock()
	as.dac = dac
}

// SetKeepAliveLevel sets the peak amplitude of the sub-audible keep-alive
// dither (0 disables). Used to tune the level that stops the host audio amp
// powering down during silence without becoming audible.
func (as *AudioSystem) SetKeepAliveLevel(level int16) {
	if level < 0 {
		level = 0
	}
	as.keepAlive = level
}

// Close closes the audio system and releases resources.
func (as *AudioSystem) Close() error {
	as.Stop()
	_ = as.StopRecording()
	return nil
}

// Reset clears the beeper sample queue and re-seeds it with the
// startup silence cushion. Used on machine reset so the new session
// doesn't start with stale audio in the buffer AND immediately
// benefits from the same cushion that startup gets.
func (as *AudioSystem) Reset() {
	if as.silent {
		// Pump-driven systems keep the queue empty by construction; an
		// 80 ms silence cushion would land mid-recording on every reboot.
		as.queueMu.Lock()
		as.queueHead, as.queueTail, as.queueSize = 0, 0, 0
		as.lastL, as.lastR = 0, 0
		as.queueMu.Unlock()
		return
	}
	as.prefillSilence()
}

// StartRecording opens path for writing and begins capturing the mixed
// audio output as a 16-bit stereo PCM WAV file at SampleRate. If a
// recording is already in progress it is finalised first.
func (as *AudioSystem) StartRecording(path string) error {
	if err := as.StopRecording(); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create wav file: %w", err)
	}
	if err := writeWavHeader(f, 0, ChannelCount, SampleRate, 16); err != nil {
		_ = f.Close()
		_ = os.Remove(path)
		return fmt.Errorf("write wav header: %w", err)
	}
	as.recMu.Lock()
	as.recFile = f
	as.recSamples = 0
	as.recMu.Unlock()
	return nil
}

// maxWavFrames is the largest number of stereo 16-bit frames we can
// capture before either of the WAV header's uint32 size fields would
// overflow. About 6.8 hours at 44.1kHz; writeRecording stops
// appending past this point.
const maxWavFrames uint64 = (0xFFFFFFFF - 36) / (ChannelCount * 2)

// StopRecording finalises any in-progress recording.
func (as *AudioSystem) StopRecording() error {
	as.recMu.Lock()
	f := as.recFile
	samples := as.recSamples
	as.recFile = nil
	as.recSamples = 0
	as.recMu.Unlock()
	if f == nil {
		return nil
	}
	if _, err := f.Seek(0, 0); err != nil {
		_ = f.Close()
		return err
	}
	if err := writeWavHeader(f, uint32(samples), ChannelCount, SampleRate, 16); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

// IsRecording reports whether a WAV recording is currently in progress.
func (as *AudioSystem) IsRecording() bool {
	as.recMu.Lock()
	defer as.recMu.Unlock()
	return as.recFile != nil
}

// writeRecording appends an interleaved stereo buffer to the active WAV file.
// recSamples counts FRAMES, matching the header's sample-count field, so an
// odd trailing slot is dropped rather than written as half a frame.
func (as *AudioSystem) writeRecording(interleaved []int16) {
	as.recMu.Lock()
	defer as.recMu.Unlock()
	if as.recFile == nil {
		return
	}
	remaining := maxWavFrames - as.recSamples
	if remaining == 0 {
		return
	}
	frames := uint64(len(interleaved) / ChannelCount)
	if frames > remaining {
		frames = remaining
	}
	samples := interleaved[:frames*ChannelCount]

	need := len(samples) * 2
	if cap(as.recScratch) < need {
		as.recScratch = make([]byte, need)
	}
	buf := as.recScratch[:need]
	for i, s := range samples {
		binary.LittleEndian.PutUint16(buf[i*2:], uint16(s))
	}
	if _, err := as.recFile.Write(buf); err != nil {
		_ = as.recFile.Close()
		as.recFile = nil
		return
	}
	as.recSamples += frames
}

// writeWavHeader writes a 44-byte canonical PCM WAV header.
func writeWavHeader(f *os.File, sampleCount uint32, channels uint16, sampleRate uint32, bitsPerSample uint16) error {
	byteRate := sampleRate * uint32(channels) * uint32(bitsPerSample) / 8
	blockAlign := channels * bitsPerSample / 8
	dataSize := sampleCount * uint32(blockAlign)
	riffSize := 36 + dataSize

	hdr := make([]byte, 44)
	copy(hdr[0:4], []byte("RIFF"))
	binary.LittleEndian.PutUint32(hdr[4:8], riffSize)
	copy(hdr[8:12], []byte("WAVE"))
	copy(hdr[12:16], []byte("fmt "))
	binary.LittleEndian.PutUint32(hdr[16:20], 16)
	binary.LittleEndian.PutUint16(hdr[20:22], 1)
	binary.LittleEndian.PutUint16(hdr[22:24], channels)
	binary.LittleEndian.PutUint32(hdr[24:28], sampleRate)
	binary.LittleEndian.PutUint32(hdr[28:32], byteRate)
	binary.LittleEndian.PutUint16(hdr[32:34], blockAlign)
	binary.LittleEndian.PutUint16(hdr[34:36], bitsPerSample)
	copy(hdr[36:40], []byte("data"))
	binary.LittleEndian.PutUint32(hdr[40:44], dataSize)

	_, err := f.Write(hdr)
	return err
}
